### ISSUE TITLE
可以发布到npm或者github release吗

### ISSUE THREAD

**Issue by kls1991** [thqby/vscode-autohotkey2-lsp#437]
如题。我在配置neovim，找了半天在哪里下载这个插件，最后是在vscode market里找到的...

如果能发布到github release或者npm，对于vscode以外的编辑器，通过nvim-mason这样的外部包管理器就能很方便的安装和更新了

我接触编程时间不长，不知道会不会很麻烦......

最后感谢大佬，我是照着issue里抄的配置，自己都没想过能成功，居然啥都好使......非常感谢

**Comment by thqby** [comment]
https://github.com/thqby/vscode-autohotkey2-lsp#use-in-other-editors

安装更新脚本
```bat
mkdir vscode-autohotkey2-lsp
cd vscode-autohotkey2-lsp
curl -L -o install.js https://raw.githubusercontent.com/thqby/vscode-autohotkey2-lsp/main/tools/install.js
node install.js
```

**Comment by thqby** [comment]
有些包管理器支持从marketplace.visualstudio.com下载更新

**Comment by thqby** [comment]
忘了是那个了

**Comment by kls1991** [comment]
大佬我又研究了一下，mason.nvim这个包管理器挺全面的，支持自定义构建脚本，我试了一下成功了，要提交的大概是这样

vscode-autohotkey2-lsp/package.yaml:
```yaml
---
name: vscode-autohotkey2-lsp
description: Autohotkey v2 Language Support using vscode-lsp.
homepage: https://github.com/thqby/vscode-autohotkey2-lsp
licenses:
  - Apache-2.0
languages:
  - AutoHotKey
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/thqby/vscode-autohotkey2-lsp@3602d19df5a2c55d068ae0c7887c6b18f3c8d64f
  build:
    - target: win
      run: |
        cp ./tools/install.js .
        rm * -Exclude install.js -Recurse -Force
        node ./install.js

```

请问我可以提交吗，如果可以的话license写什么？
