### ISSUE TITLE
Syntax Highlighting in Helix Editor

### ISSUE THREAD

**Issue by kdalanon** [thqby/vscode-autohotkey2-lsp#696]
I was able to add the LSP to Helix Editor by following the [Use in other editors](https://github.com/thqby/vscode-autohotkey2-lsp/blob/main/README.md#use-in-other-editors) guide.

![Image](https://github.com/user-attachments/assets/f80d15a9-c3e4-4ecf-b7d5-3684d8417002)

However, I can't seem to enable syntax highlighting. How can I do that?

Here is my [languages.toml](https://docs.helix-editor.com/languages.html) file:

```toml
[[language]]
name = "ahk2"
scope = "source.ahk2"
language-servers = ["ahk-v2-lsp"]
file-types = ["ahk"]
comment-tokens = ";"
    
[language-server.ahk-v2-lsp]
command = "node"
args = ["c:\\Users\\Username\\Documents\\AutoHotkey Scripts\\vscode-autohotkey2-lsp\\server\\dist\\server.js", "--stdio"]
```
